In [1]:
import numpy as np
import time
from math import ceil
import  random

def start_measuring(action):
    start = time.time()
    action()
    end = time.time()
    return f"{end - start:.4f}s"

def compare_algos(numpy, own):
     return f"numpy: {start_measuring(numpy)} ", f"own: {start_measuring(own)}"


*Вправа 2.* Вводиться число *n*. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці *n×n*, використовуючи слайсінг.

In [2]:
def task_2_numpy_algo(n):
    matrix = np.zeros((n,n), int)
    matrix[::2,::2] = 1
    matrix[1::2,1::2] = 1
    return matrix
    #print(matrix)

def task_2_algo(n):
    matrix = [[0]*n for _ in range(0, n)]
    line1 = [i % 2 for i in range(1, n+1)]
    line2 = [i % 2 for i in range(0, n)]
    matrix[::2] = [line1 for _ in range(0, len(matrix[::2]))]
    matrix[1::2] = [line2 for _ in range(0, len(matrix[1::2]))]
    return matrix
    #for i in matrix: print(i)

def task_2():
    print(task_2_numpy_algo(10))
    for i in task_2_algo(10): print(i)
    try:
        n = int(input())
    except ValueError:
        return "Enter only number!"

    return compare_algos(lambda : task_2_numpy_algo(n), lambda : task_2_algo(n))

In [3]:
task_2() 

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


 10000


('numpy: 0.1604s ', 'own: 1.4234s')

Швидше в 10 разів numpy

*Вправа 3.* Вводяться 4 числа *n, m, r, c*. Вивести масив розміру *n×m*, в якому в кожному рядку з номером *r* і в кожному стовпчику з номером *c* стоять 0, а інші елементи дорівнюють 1.

In [4]:
def task_3_numpy_algo(n, m, r, c):
    matrix = np.ones((n,m), int)
    matrix[r-1] = np.zeros(m)
    matrix[::, c-1] = 0
    return matrix
    #print(matrix)

def task_3_algo(n, m, r, c):
    matrix = [
        [0 if j - r + 1 == 0 or i - c + 1 == 0 else 1 for i in range(m)]
        for j in range(n)
    ]
    return matrix
    #for i in matrix: print(i)

def task_3():
    print(task_3_numpy_algo(10, 9, 2, 3))
    for i in task_3_algo(10, 9, 2, 3): print(i)
    inputs = input().split(" ")
    if len(inputs) != 4:
        return "There must be only 4 numbers!"
    nums = []
    for i in inputs:
        try:
            nums.append(int(i))
        except ValueError:
            return "Enter only number!"
    n, m, r, c = nums
    if r > n or c > m:
        return "Indexes out of range"

    return compare_algos(lambda : task_3_numpy_algo(n, m, r, c), lambda : task_3_algo(n, m, r, c))

In [5]:
task_3()

[[1 1 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1]]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1]


 10000 1000 500 300


('numpy: 0.0135s ', 'own: 1.6195s')

*Вправа 5.* Вводиться число *n*. Вивести масив розміру *n×n*, в
якому в рядках з парними індексами стоять 1, а в інших – 0.

In [26]:
def task_5_numpy_algo(n):
    matrix = np.zeros((n,n), int)
    matrix[1::2, ::] = 1
    return matrix
    #print(matrix)

def task_5_algo(n):
    matrix = [[0]*n for _ in range(0, n)]
    matrix[1::2] = [[1]*n for _ in matrix[::2]]
    return matrix
    #for i in matrix: print(i)

def task_5():
    print(task_5_numpy_algo(10))
    for i in task_5_algo(10): print(i)
    try:
        n = int(input())
    except ValueError:
        return "Enter only number!"

    return compare_algos(lambda : task_5_numpy_algo(n), lambda : task_5_algo(n))

In [27]:
task_5()

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


 10000


('numpy: 0.0870s ', 'own: 2.3222s')

Швидше в 26 разів numpy

*Вправа 9.* Вводиться число *n*. Створити масив значень від *n* до 0.

In [8]:
def task_9_numpy_algo(n):
    array = np.arange(n, -1, -1)
    return array
    #print(array)

def task_9_algo(n):
    array = [i for i in range(n, -1, -1)]
    return array
    #print(array)

def task_9():
    print(task_9_numpy_algo(10))
    print(task_9_algo(10))
    try:
        n = int(input())
    except ValueError:
        return "Enter only number!"

    return compare_algos(lambda : task_9_numpy_algo(n), lambda : task_9_algo(n))

In [9]:
task_9()

[10  9  8  7  6  5  4  3  2  1  0]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


 1000000


('numpy: 0.0020s ', 'own: 0.0693s')

Швидше в 24 разів numpy

*Вправа 13.* Розмістити на полі *8×8* нулі та одиниці в шахматному
порядку, використовуючи функцію повторення (*).

In [10]:
def task_13_numpy_algo():
    matrix = np.zeros((8,8), int)
    matrix[::2] = [0,1] * 4
    matrix[1::2] = [1,0] * 4
    print(matrix)

def task_13_algo():
    matrix = [[0]*8 for _ in range(0, 8)]
    matrix[::2] = [[0, 1]*4 for _ in matrix[::2]]
    matrix[1::2] = [[1, 0]*4 for _ in matrix[1::2]]
    for i in matrix: print(i)

def task_13():
    return compare_algos(lambda : task_13_numpy_algo(), lambda : task_13_algo())

In [11]:
task_13()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


('numpy: 0.0000s ', 'own: 0.0000s')

*Вправа 14.* Розмістити на полі *8×8* нулі та одиниці в шахматному
порядку, використовуючи функцію **numpy tile()**.

In [12]:
def task_14_numpy_algo():
    matrix = np.zeros((8,8), int)
    matrix[::2] = np.tile([0,1], 4)
    matrix[1::2] = np.tile([1,0], 4)
    print(matrix)

def task_14_algo():
    matrix = [[0]*8 for _ in range(0, 8)]
    matrix[::2] = [[0, 1]*4 for _ in matrix[::2]]
    matrix[1::2] = [[1, 0]*4 for _ in matrix[1::2]]
    for i in matrix: print(i)

def task_14():
    return compare_algos(lambda : task_14_numpy_algo(), lambda : task_14_algo())

In [13]:
task_14()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


('numpy: 0.0010s ', 'own: 0.0000s')

*Вправа 16.* Заповнити вектор значеннями від 0 до *n*. Всі значення,
що більші за *n*/4 та менші за 3*n*/4 замінити нулями.

In [14]:
def task_16_numpy_algo(n):
    array = np.arange(0, n+1)
    array[ceil(n/4)+1:ceil(3*n/4)] = 0
    return array
    #print(array)

def task_16_algo(n):
    array = [i for i in range(0, n+1)]
    for i in range(ceil(n/4)+1, ceil(3*n/4)):
        array[i] = 0
    return array
    #print(array)

def task_16():
    print(task_16_numpy_algo(20))
    print(task_16_algo(20))
    try:
        n = int(input())
    except ValueError:
        return "Enter only number!"
    return compare_algos(lambda : task_16_numpy_algo(n), lambda : task_16_algo(n))

In [15]:
task_16()

[ 0  1  2  3  4  5  0  0  0  0  0  0  0  0  0 15 16 17 18 19 20]
[0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 16, 17, 18, 19, 20]


 1000000


('numpy: 0.0020s ', 'own: 0.0747s')

*Вправа 17.* Заповнити вектор значеннями від 0 до *n*. Замінити
знаки для всіх значень, що менші за *n*/2 та більші за 3*n*/4 на
протилежні.

In [16]:
def task_17_numpy_algo(n):
    array = np.arange(0, n + 1)
    array[0:ceil(n / 2)] *= -1
    array[ceil(3*n / 4):] *= -1
    return array
    # print(array)


def task_17_algo(n):
    array = [i for i in range(0, n + 1)]
    for i in range(0, ceil(n / 2)):
        array[i] *= -1
    for i in range(ceil(3*n / 4), n + 1):
        array[i] *= -1
    return array
    # print(array)


def task_17():
    print(task_17_numpy_algo(20))
    print(task_17_algo(20))
    try:
        n = int(input())
    except ValueError:
        return "Enter only number!"
    return compare_algos(lambda: task_17_numpy_algo(n), lambda: task_17_algo(n))


In [17]:
task_17()

[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9  10  11  12  13  14 -15 -16 -17
 -18 -19 -20]
[0, -1, -2, -3, -4, -5, -6, -7, -8, -9, 10, 11, 12, 13, 14, -15, -16, -17, -18, -19, -20]


 1000000


('numpy: 0.0030s ', 'own: 0.1177s')

*Вправа 20.* Згенерувати вектор із *n* випадкових елементів, що
лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [18]:
def task_20_numpy_algo(n):
    array = np.random.rand(n)
    #print(f"Початковий вектор {array:}")
    array[np.argmax(array)] = 0
    #print(f"Змінений вектор {array}")
    return array


def task_20_algo(n):
    array = [random.random() for _ in range(0, n)]
    #print(f"Початковий вектор {array:}")
    max_index = 0
    for i in range(1, n):
        if array[i] > array[max_index]:
            max_index = i
    array[max_index] = 0
    #print(f"Змінений вектор {array}")
    return array


def task_20():
    print(task_20_numpy_algo(10))
    print(task_20_algo(10))
    try:
        n = int(input())
    except ValueError:
        return "Enter only number!"
    return compare_algos(lambda: task_20_numpy_algo(n), lambda: task_20_algo(n))

In [19]:
task_20()

[0.         0.05739518 0.20435486 0.28349305 0.40927626 0.14423592
 0.37017804 0.25978257 0.41181677 0.22147566]
[0.3223109042505168, 0.7373950969290836, 0.5098413926074994, 0, 0.9185328147662375, 0.8354055739612152, 0.9100869698327257, 0.11701273602320117, 0.4558662815572604, 0.9454183804530546]


 1000000


('numpy: 0.0080s ', 'own: 0.1718s')

##### Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
1. матричного множення;
2. оберненої матриці;
3. функції numpy.linalg.solve().

$$
\left\{
    \begin{array}\\
        x_1 + 2x_2 + 3x_3 - 2x_4 = 6 \\
        x_1 - x_2 - 2x_3 - 3x_4 = 8 \\
        3x_1 + 2x_2 - x_3 + 2x_4 = 4 \\
        2x_1 - 3x_2 + 2x_3 + x_4 = -8
    \end{array}
\right.
$$

In [20]:
def kramer_algo(matrix, vector):
    n = len(vector)
    det = np.linalg.det(matrix)
    res = []
    for i in range(0, n):
        sub = np.copy(matrix)
        sub[:,i]=vector
        res.append(np.linalg.det(sub)/det)

    return np.array(res)


def task_linear():
    matrix = np.array([  [1, 2,  3,  -2],
                [1, -1, -2, -3],
                [3, 2,  -1, 2],
                [2, -3, 2,  1]])
    vector = np.array([6, 8, 4, -8])

    print(f"matrix = {matrix}\nvector = {vector}\n")

    res = kramer_algo(matrix, vector)
    print(f"res = {res}\n")

    vector_mul = matrix.dot(res)
    print(f"matrix * res = {vector_mul} == vector  {np.allclose(vector, vector_mul)}")

    res_inv = np.linalg.inv(matrix).dot(vector)
    print(f"matrix^-1 * vector = {res_inv} == res  {np.allclose(res, res_inv)}")

    res_lin = np.linalg.solve(matrix, vector)
    print(f"linalg.solve = {res_lin} == res  {np.allclose(res, res_lin)}")


In [21]:
task_linear()

matrix = [[ 1  2  3 -2]
 [ 1 -1 -2 -3]
 [ 3  2 -1  2]
 [ 2 -3  2  1]]
vector = [ 6  8  4 -8]

res = [ 1.125   1.9375 -1.125  -2.1875]

matrix * res = [ 6.  8.  4. -8.] == vector  True
matrix^-1 * vector = [ 1.125   1.9375 -1.125  -2.1875] == res  True
linalg.solve = [ 1.125   1.9375 -1.125  -2.1875] == res  True


Обчислити значення матричного виразу:
1. з використанням універсальних функцій бібліотеки NumPy.
2. за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
3. для обох випадків підрахувати час виконання скрипту та
зробити висновок.
Порівняти всі рішення за допомогою функції numpy.allclose().

$$
3A - (A - 2B)B \\\\
де  A = \begin{pmatrix} 4 & 5 & -2 \\ 3 & -1 & 0 \\ 4 & 2 & 7 \end{pmatrix}, 
B = \begin{pmatrix} 2 & 1 & -1 \\ 0 & 1 & 3 \\ 5 & 7 & 3 \end{pmatrix}
$$

In [24]:
from copy import deepcopy


def task_matrix_numpy_algo(matrix_a, matrix_b):
    np_a = np.array(matrix_a)
    np_b = np.array(matrix_b)
    res = 3 * np_a - (np_a - 2 * np_b).dot(np_b)
    # print(res)
    return res


def matrix_constant(constant, matrix):
    res = deepcopy(matrix)
    for i in range(0, len(res)):
        for j in range(0, len(res)):
            res[i][j] *= constant

    return res


def matrix_addition(matrix_a, matrix_b):
    res = deepcopy(matrix_a)
    for i in range(0, len(res)):
        for j in range(0, len(res)):
            res[i][j] += matrix_b[i][j]

    return res


def matrix_multiplication(matrix_a, matrix_b):
    res = [[0]*len(matrix_a) for _ in range(0, len(matrix_a))]
    for i in range(0, len(res)):
        for j in range(0, len(res)):
            for k in range(0, len(res)):
                res[i][j] += matrix_a[i][k] * matrix_b[k][j]

    return res

def task_matrix_algo(matrix_a, matrix_b):
    res = matrix_addition(
        matrix_constant(3, matrix_a),
        matrix_constant(-1,matrix_multiplication(
                                matrix_addition(
                                    matrix_a,
                                    matrix_constant(-2, matrix_b)),
                                matrix_b)))
    # print(res)
    return res


def task_matrix():
    matrix_a = [[4, 5, -2],
              [3, -1, 0],
              [4, 2, 7]]
    matrix_b =  [[2, 1, -1],
              [0, 1, 3],
              [5, 7, 3]]

    res_num = task_matrix_numpy_algo(matrix_a, matrix_b)
    res_algo = task_matrix_algo(matrix_a, matrix_b)
    print(res_algo)
    print(f"res_num == res_algo  {np.allclose(res_num, res_algo)}")

    return compare_algos(
        lambda: task_matrix_numpy_algo(matrix_a, matrix_b),
        lambda: task_matrix_algo(matrix_a, matrix_b))

In [25]:
task_matrix()

[[12, 12, -15], [33, 39, 30], [19, 17, 48]]
res_num == res_algo  True


('numpy: 0.0000s ', 'own: 0.0000s')